### ISSUE TITLE
How does this mod actually work?

### ISSUE THREAD

**Issue by jjrush** [RykeDaxter/MycoMerger#1]
Hit the mycologist a few times with this mod installed and it doesn't seem to let me pick and choose two different creatures to fuse. It just gives me the same selection as vanilla. Am I just using it wrong?

Didn't know where else to ask this question so I'm asking here.

**Comment by RykeDaxter** [comment]
MycoMerger is an API. It doesn't do anything by itself and requires other mods to make use of its capabilities to merge different creatures.

The feature to allow any two cards to be merged requires Unity asset editing of the Mycologist event which is outside of my knowledge and was therefore not included although the capability does exist. Making use of MycoMerger to create a non-vanilla merge has to be specified by another mod due to this.

**Comment by jjrush** [comment]
Gotcha. This is what I roughly gathered from reading the info you left on the mod but wasn't 100% sure so figured I'd ask. Thanks!
